### ISSUE TITLE
"Download" URL incorrect in the metadata

### ISSUE THREAD

**Issue by mgorny** [vsajip/sarge#54]
**Describe the bug**
The URL to downloads misses your username on GitHub.

**To Reproduce**
1. Go to https://pypi.org/project/sarge/
2. Click on 'Download'
3. See error 404

**Expected behavior**
Landing on the right repo ;-).

**Screenshots**
n/a

**Environment**
 - OS, including version: Gentoo Linux
 - Version of this library: 1.0.7

**Additional information**
n/a

**Comment by mgorny** [comment]
That said, it's not a big deal for me, I just supposed you wanted to fix it.

**Comment by vsajip** [comment]
Yes, thanks for spotting it. I'll issue a point update :blush:

**Comment by vsajip** [comment]
Fixed with release 0.1.7.post1.
