### ISSUE TITLE
get exception when  _async=True

### ISSUE THREAD

**Issue by Maziar123** [vsajip/sarge#57]
Hi

when run in with _async=true

cmd = 'eco "Hello " '
p = sarge.run(cmd, async_=True)

no any way catch & get massage of exception in run ?
for example when up command have ValueError ....

i can not find way to use try except in async run and also return "p"   have not any property to show error when run it ....

**Comment by vsajip** [comment]
Are you referring to the fact that there is a typo in the command? "eco" rather than "echo"?

**Comment by vsajip** [comment]
Documented [here](https://docs.red-dove.com/sarge/tutorial.html#handling-errors-in-asynchronous-mode).

**Comment by Maziar123** [comment]
> Are you referring to the fact that there is a typo in the command? "eco" rather than "echo"?


yes. this is one sample of fault command when in async mode can't handle errors.

**Comment by vsajip** [comment]
Did you try the fix I did in f6f1a51?

**Comment by Maziar123** [comment]
better version in pipeline ?

    @property
    def Exceptions(self) -> List[Exception]:
        """
        A list of the Exceptions for all the command which have been run.
        """
        result = []
        if self.commands:
            for c in self.commands:
                exp = None
                if c is not None:
                    exp = c.exception
                if exp is not None:
                    result.append(exp)
        return result
